task :eslint do
  system "./node_modules/.bin/eslint ../js-task-manager/*.js"
end

# task :mocha do
#   system "/usr/local/lib/node_modules/.bin/mocha spec/*.js"
# end

# add :mocha
task default: [:eslint]
